In [69]:
import numpy as np


nlist = np.array([[
            [[1,2,3,4],[5,6,7,8]],
            [[9,10,11,12],[13,14,15,16]]],
        [
            [[17,18,19,20],[21,22,23,24]],
            [[25,26,27,28],[29,30,31,32]]
        ]])





lu = nlist[:,0:1,0:1,:]
ru = nlist[:,0:1,1:2,:]
ld = nlist[:,1:2,0:1,:]
rd = nlist[:,1:2,1:2,:]
nn = np.stack([lu[0],ru[0],ld[0],rd[0]])
print("V\n", np.vstack((lu,ru,ld,rd)))
print("H\n", np.hstack((lu,ru,ld,rd)))
print("D\n", np.dstack((lu,ru,ld,rd)))
#  for i in range(1,len(lu)):
#     nn = np.concatenate([nn, np.stack([ru[i],ld[i],rd[i]])],axis=0)
# print(nn)
# first_new = np.concatenate([,,,],axis=0)
# print(first_new)
# print(first_new.shape)
# nnlist=[]
# for i in nlist:
#     # print("> ",i)
#     half = np.split(i, 2, axis=1)
#     for j in np.split(half[0], 2, axis=2):
#         print(j.shape)
#         nnlist.append(j)
#     for j in np.split(half[1], 2, axis=2):
#         print(j.shape)
#         nnlist.append(j)
# nnlist = np.concatenate(nnlist,axis=0)
# print(nnlist.shape)
# print(nnlist)

# # print(half[0].shape)
# # print(half[1].shape)
# # print(np.split(half[i], 2, axis=2) for i in range(2))
# print(nnlist)
# half_half2 = np.split(half[1], 2, axis=2)
# nnlist = [x for x in (np.split(half[i], 2, axis=2) for i in range(2)) ]
# print(nnlist)
# print(nnlist[0].shape)


V
 [[[[ 1  2  3  4]]]


 [[[17 18 19 20]]]


 [[[ 5  6  7  8]]]


 [[[21 22 23 24]]]


 [[[ 9 10 11 12]]]


 [[[25 26 27 28]]]


 [[[13 14 15 16]]]


 [[[29 30 31 32]]]]
H
 [[[[ 1  2  3  4]]

  [[ 5  6  7  8]]

  [[ 9 10 11 12]]

  [[13 14 15 16]]]


 [[[17 18 19 20]]

  [[21 22 23 24]]

  [[25 26 27 28]]

  [[29 30 31 32]]]]
D
 [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 16]]]


 [[[17 18 19 20]
   [21 22 23 24]
   [25 26 27 28]
   [29 30 31 32]]]]


In [68]:
import numpy as np

print()

[[1]
 [1]
 [2]
 [2]
 [3]
 [3]
 [4]
 [4]
 [5]
 [5]
 [6]
 [6]
 [7]
 [7]
 [8]
 [8]
 [1]
 [1]
 [2]
 [2]
 [3]
 [3]
 [4]
 [4]
 [5]
 [5]
 [6]
 [6]
 [7]
 [7]
 [8]
 [8]]
